language: cpp
matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      before_script:
        - sudo apt-get -y install libglew-dev xorg-dev
        - mkdir build
        - cd build
        - cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DSPATIUMGL_MODULE_GFX3D=ON -DSPATIUMGL_MODULE_GFX3D_OPENGL=ON -DSPATIUMGL_MODULE_IO_LAS=ON -DSPATIUMGL_APP_PCVIEWER=OFF
      script:
        - make
        - make test
    - os: windows
      before_script:
        - mkdir build
        - cd build
        - cmake .. -G "Visual Studio 15 2017 Win64" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON -DSPATIUMGL_MODULE_GFX3D=ON -DSPATIUMGL_MODULE_GFX3D_OPENGL=ON -DSPATIUMGL_MODULE_IO_LAS=ON -DSPATIUMGL_APP_PCVIEWER=OFF
      script:
        - cmake --build . --target ALL_BUILD --config Release
        - ctest -C "Release"
    - os: osx
      osx_image: xcode11
      compiler: clang
      before_script:
        - mkdir build
        - cd build
        - cmake .. -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DSPATIUMGL_MODULE_GFX3D=ON -DSPATIUMGL_MODULE_GFX3D_OPENGL=OFF -DSPATIUMGL_MODULE_IO_LAS=OFF -DSPATIUMGL_APP_PCVIEWER=OFF
      script:
        - make
#        - make test
